---
# This playbook deploys ta simple LAMP stack

- name: Make sure the correct timezone is setup and ntp is running
  hosts: all
  vars_files:
    - "roles/lamp_simple/group_vars/all"
  remote_user: ec2-user
  roles:
    - lamp_simple

