---
# This playbook installs NTP

- name: Install ntp 
  yum:
    name: ntp 
    state: present

- name: Configure ntp file
  template: 
    src: ntp.conf.j2 
    dest: /etc/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service: 
    name: ntpd 
    state: started 
    enabled: yes
    
- name: set timezone to Europe/Amsterdam
  timezone:
    name: Europe/Amsterdam
    
- hostname:
    name: pon01
